action_list: 
    number_of_targets: 16

    action_0: 
        action_type: "pose"
        translation: [0.33, 0.03, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 2.5
  
    action_1: 
        action_type: "pose"
        translation: [0.37, -0.19, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.3

    action_2: 
        action_type: "pose"
        translation: [0.37, 0.16, 0.42]
        orientation: [0.0, 0.0, 0.0]
        duration: 2.0

    action_3:
        action_type: "pose"
        translation: [0.40, 0.16, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.0

    action_4: 
        action_type: "pose"
        translation: [0.36, -0.19, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.0

    action_5:
        action_type: "pose"
        translation: [0.48, 0.03, 0.50]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.5

    action_6:
        action_type: "pose"
        translation: [0.48, 0.03, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.0

    action_7:
        action_type: "pose"
        translation: [0.48, -0.19, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.0

    action_8: 
        action_type: "pose"
        translation: [0.33, 0.03, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 2.0
  
    action_9: 
        action_type: "pose"
        translation: [0.37, -0.19, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.5

    action_10: 
        action_type: "pose"
        translation: [0.37, 0.16, 0.42]
        orientation: [0.0, 0.0, 0.0]
        duration: 2.0

    action_11:
        action_type: "pose"
        translation: [0.40, 0.16, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.0

    action_12: 
        action_type: "pose"
        translation: [0.38, -0.19, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.5

    action_13:
        action_type: "pose"
        translation: [0.45, -0.03, 0.50]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.3

    action_14:
        action_type: "pose"
        translation: [0.45, -0.03, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.0

    action_15:
        action_type: "pose"
        translation: [0.45, -0.19, 0.35]
        orientation: [0.0, 0.0, 0.0]
        duration: 1.0
